ch.elexis.core.data/src/ch/elexis/data/PersistentObject.java

Discovered that the globalCfg did not get correctly initialized when the database was specified via System-Properties on the command line.

[4139]Fix loading globalCfg when connecting via SystemProperties

---

ch.elexis.core.data/src/ch/elexis/data/Konsultation.java

A default diagnosis should be added whether you create a new kons via Fall.neueKonsultation or Konsultation.newKons(initialText)

[5612]New kons always add default diagnosis

---

ch.elexis.core.product/Elexis.product
ch.elexis.core.ui.p2/plugin_customization.ini
ch.elexis.core.ui.p2/src/ch/elexis/core/ui/p2/internal/PreferenceInitializer.java
ch.elexis.core.ui.p2/src/ch/elexis/core/ui/p2/policy/ElexisCloudPolicy.java

Habe folgendes festgestellt:
*  ch.elexis.core.ui.p2 wird als Plugin nicht gestartet. Deshalb werden die Prozeduren für die Initialisirung nie aufgerufen
*  plugin_customization.ini definiert Variablen für falsches Plugin org.eclipse.equinox.p2.examples.rcp.cloud/
*   Installation von features läuft nur, wenn
**      "Contact all update sites" deaktviert ist
**      NUR elexis-3-base als P2-Site enabled ist

[8768] Load correctly p2 configuration

---

bundles/ch.elexis.core.data/src/ch/elexis/data/PersistentObject.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/util/SqlWithUiRunner.java

Das sollte das von Gerry gesehene Problem lösen, welche es am 7.1.19 auf der Entwicklerliste gepostet hat:
> Das störende Fenster ist nicht das Splash-Popup, sondern die
Hintergrund Shell der Fortschrittsanzeige des Datenbank-Updates. Da zu
diesem Zeitpunkt noch kein Elexis-Fenster existiert, scheint das RCP
Framework dafür eine eigene Shell zu erzeugen. Oder irgendwo in Elexis
ist code, der das tut.
Da das Update so schnell durchlauft, kriegt man es meistens nicht mit
(und kriegt auch nicht die Fehlermeldungen angezeigt), aber die Shell
bleibt stehen.
Beweis: Wenn man die Methode doUpate in DBUpdate.java auskommentiert,
erscheint dieses Fenster nicht mehr.
Vorschlag:
- Wenn der Update-Prozess auf die Nase fällt, sollte der User das als
Meldung angezeigt bekommen. Vielleicht ist es ja …

[14835] Show dialog when dbupdate fails. User may continue

---

bundles/ch.elexis.core.data/src/ch/elexis/core/data/constants/ElexisSystemPropertyConstants.java
bundles/ch.elexis.core.data/src/ch/elexis/data/Mandant.java
bundles/ch.elexis.core.data/src/ch/elexis/data/PersistentObject.java
bundles/ch.elexis.core.data/src/ch/elexis/data/PersistentObjectUtil.java

I tested it (after installing it into the work subdirectory) by using the following bash commands
```
rm -rfv ~/elexis/first.h2.db ~/elexis/demoDB
work/Elexis3 -vmargs -Dch.elexis.dbFlavor=h2 -Dch.elexis.dbSpec='jdbc:h2:~/elexis/first;AUTO_SERVER=TRUE' -Dch.elexis.dbUser=sa -Dch.elexis.dbPw='' \
-Dch.elexis.firstMandantName=test \
-Dch.elexis.firstMandantPassword=test \
-Dch.elexis.firstMandantEmail=test@invalid.org \
-Dch.elexis.username=test \
-Dch.elexis.password=test 
```

[14812] Allow bypassing FirstMandantDialog

---

bundles/ch.elexis.core.data/src/ch/elexis/data/LabResult.java

- The method getForDate uses the deprecated field "date".
- To get the actual labresult for medelexis I needed the possibility to fetch with the field observationtime instead of date

[14968] SSKO 2: Automatisches Befüllen Header Composite 

---

bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
bundles/ch.rgw.utility/src/ch/rgw/tools/TimeTool.java
tests/ch.rgw.utility.tests/src/ch/rgw/tools/Test_TimeTool.java

I have added an RCPTT GUI-Test which changes the kons date to exercise all differents variants (before, after,day,week,month,year).
To be able to run the RCPTT I adde a new helper function daysFromNow in TimeTools .

[14803] Fix timetool properties for getDurationAsString if language is not german

---

.travis.yml
ch.elexis.core.p2site/pom.xml
ch.elexis.core.p2site/start_h2_first_linux_x86_64.sh
pom.xml

Ich habe mich immer wieder geärgert, wenn (was for allem in NoPo-Branch vorkam) die erstellte Elexis3 Applikation nicht mal aufstartet und meine RCPTT-GUI-Tests dann nicht laufen.
Deshalb habe ich ein kleines Skript geschrieben, das (allerdings nur unter Linux x86-64) Elexis3 mit einer leeren DB startet, einen ersten Mandanten anlegt. Wenn nicht schlägt es fehl.
Deshalb sollten danach die gitlab und travis build fehlschlagen, wenn man Elexis3 nicht korrekt aufstarten kann.
In einem zweiten Schritt werde ich dann die Travis-Builds noch ausbauen, dass sowohl mit Java8 als auch mit Java11 getestet wird.

Ensure that Elexis3 can start with a clean H2 database

---

bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/processor/ElexisProcessor.java

Über den Perspektivenmanagement lassen sich "alte" Perspektiven entfernen. Doch eine automatisierte Lösung dafür wäre vermutlich komfortabler.
Dies veranschaulicht eine Möglichkeit alte Model-Elemente in der Workbench.xmi zu entfernen. Wie die Lösung genau sein soll, gehört auspezifiziert. Vl über eine seperate Einstellungssteite, über ein VM-Param, oder wie diese Lösung statisch beim Programmstart.

[15402] Möglichkeit alte Application-Model-Elemente zu entfernen (BETA)

---

bundles/ch.elexis.core.application/plugin.xml
bundles/ch.elexis.core.application/src/ch/elexis/core/application/perspectives/BBSPerspective.java

Die ID musste auf "ch.elexis.SchwarzesBrettV1.0" verändert werden, da sonst der Perspektiven Code nicht ausgeführt wird, wenn diese Perspektive schon in dem Model vorhanden ist. Die "fehlerhafte" Perspektive kann mit dem PerspektivenManagement entfernt werden. Zusätzlich habe ich auch ein Code im ElexisProzessor bereitgestellt der die Fehlerhafte Perspektive "ch.elexis.SchwarzesBrett" aus dem Model automatisch entfernt.

[15402] Perspektive "Schwarzes Brett" unbrauchbar

---

bundles/ch.elexis.core.application/src/ch/elexis/core/application/Desk.java
bundles/ch.elexis.core.data/src/ch/elexis/core/data/preferences/CorePreferenceInitializer.java
bundles/ch.elexis.core.data/src/ch/elexis/data/DBConnection.java
bundles/ch.elexis.core.ui.dbcheck/src/ch/elexis/core/ui/dbcheck/CheckExec.java
bundles/ch.elexis.core/src/ch/elexis/core/common/DBConnection.java
bundles/ch.rgw.utility/META-INF/MANIFEST.MF
bundles/ch.rgw.utility/src/ch/rgw/tools/JdbcLink.java

This avoids error about the obsolete mysql driver when running the ch.elexis.core.data.tests

[15471] Cleanup MySQL Driver. Use com.mysql.cj.jdb.

---

bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FallDetailBlatt2.java

This avoids
* NPE when using http://download.elexis.info/demoDB/demoDB_elexis_3.8.0.zip and starting Elexis with -nl fr_CH.
This NPE show up when accessing the patient Duck Dagobert.
I still see the warning
c.e.c.j.e.c.PrescriptionEntryTypeConverter - Unknown entry type [null] using UNKNOWN
in the log
* NPE when loading the view "Cas choisi" (aka Fall in germ ). As on must set the DB field "Bezeichnung" but display the label "Désignation"

[15019] Fix loading german demoDB_elexis_3.8.0.zip with nl fr_CH

---

bundles/ch.elexis.core.jpa/src/ch/elexis/core/jpa/model/adapter/AbstractIdModelAdapter.java
bundles/ch.elexis.core.jpa/src/ch/elexis/core/jpa/model/adapter/mixin/ExtInfoHandler.java
bundles/ch.elexis.core.model/src/ch/elexis/core/model/Contact.java
tests/ch.elexis.core.model.test/src/ch/elexis/core/model/AllModelTests.java
tests/ch.elexis.core.model.test/src/ch/elexis/core/model/MandatorTest.java

@Thomas Bitte beachte die Kommentare im Code. Der Reset sollte auch für weitere Entitäten erfolgen (ca 14 stück), evt könnte man das etwas globaler lösen, daher habe ich es dzt nur für Kontakt gemacht.
Der Testfall extInfoWithRefetch() verdeutlicht den Fehler und konnte nach dem Fix beseitigt werden.

[16648] Synchronizität von PO#ExtInfo und NoPo#ExtInfo ist nicht gegeben

---

.github/workflows/maven.yaml

Github offers free build validation on their server for commits and pull
requests.
This configuration file adds this based on the default build command to
avoid any build issue, as this is a free server this validation does not
harm even if Travis is also active.
Additional advantage is that everyone who clones this repo will also
have this action enabled so any PR received will automatically be
validated by the Github action.
Currently the test execution is disabled as the test currently fail in
the Tycho build. Once the test run locally with Tycho it should be
evaluated if the test can be included in the test run.

Adds build configuration for Github actions

---

.mvn/extensions.xml

While not strictly necessary it is recommended to keep the pomless
extension in sync with the the used Tycho version to avoid strange build
issues.

Tycho pomless extension updated to 1.7.0

---

.mvn/extensions.xml

Reverts elexis/elexis-3-core#403
Nach der Änderung starten die surefire tests nicht mehr.

Revert "Tycho pomless extension updated to 1.7.0"

---

bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/AUF2.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/AUFZeugnis.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/BBSView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/BestellBlatt.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/BestellView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/BriefAuswahl.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/DiagnosenDisplay.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FaelleView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FallDetailBlatt2.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FallDetailView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FallListeView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FavoritenComposite.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FieldDisplayView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/HistoryDisplay.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/KGPrintView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/KompendiumView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/KonsListe.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/MediVerlaufView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/ODDBView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/PatFilterImpl.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/PatHeuteView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/ReminderView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/RezeptBlatt.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/RezepteView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/ScriptView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/SearchView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/StockView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/TemplatePrintView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/TextView.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/VerrechnungsDisplay.java

Mit der JDT clean-up action, wurden @Deprecated und @Override für das
ch.elexis.core.ui.views durchgeführt. Macht die Weiterentwicklung der
Views leichter, da klar ist, welche Methoden überschrieben wurden.

Fuege fehlende @Override und @Deprecated annatationen für Views hinzu

---

.gitignore

Nach einem Tycho build tauchen bei mir die zip und tar Einträge des JREs
auf. Wahrscheinlich sollten diese von Git ignoriert werden, von daher
fügt dieser Commit sie dem .gitignore hinzu.

jre.bundles/downloaded wird .gitignore hinzugefuegt

---

bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties

verwendet
Commit löscht VerrechnungsDisplay_doNotCharge in allen
Uebersetztungsfiles

VerrechnungsDisplay_doNotCharge taucht beim Starten auf als nicht

---

bundles/ch.elexis.core.data/src/ch/elexis/data/DBConnection.java
bundles/ch.elexis.core.data/src/ch/elexis/data/PersistentObject.java
bundles/ch.elexis.core/src/ch/elexis/core/constants/ElexisSystemPropertyConstants.java
bundles/ch.elexis.core/src/ch/elexis/core/utils/CoreUtil.java

Enables H2 databases to be open while Elexis is running. Use cases:
* Inspect running Elexis-DB via Webbrowser
* Create DB-Dump while running RCPTT-GUI tests
* for the project elexis-uitest I did not find a way on howto pass a ";" to via setting to the startup parameter of elexis, as the semicolon is considered a separator of item

[21760] Force AUTO_SERVER for h2 (jpa and PO)

---

bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/preferences/Messages.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/Ablauf.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/Messages.java
bundles/ch.elexis.core/src/ch/elexis/core/preferences/Messages.java

In Ablauf.java there was a translation for "i" which must be marked as NON-NLS. With this change the tarmed importer works fine for the italian language, too.

[24368] Wrong preferences for italian broke tarmed importer

---

bundles/ch.elexis.core.data/src/ch/elexis/core/data/activator/CoreHub.java
bundles/ch.elexis.core.data/src/ch/elexis/data/PersistentObjectDataSourceActivator.java
bundles/ch.elexis.core.data/src/ch/elexis/data/Rechnung.java
bundles/ch.elexis.core.data/src/ch/elexis/data/User.java
bundles/ch.elexis.core.data/src/ch/elexis/data/XML2Database.java
bundles/ch.elexis.core.jpa.datasource/src/ch/elexis/core/jpa/datasource/internal/DataSourceConnectionParser.java
bundles/ch.elexis.core.jpa.datasource/src/ch/elexis/core/jpa/datasource/test/TestDatabaseConnection.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/commands/StartEditLocalDocumentHandler.java
bundles/ch.elexis.core/src/ch/elexis/core/services/IAppointmentService.java
bundles/ch.elexis.core/src/ch/elexis/core/utils/OsgiServiceUtil.java
bundles/ch.rgw.utility/src/ch/rgw/tools/JdbcLink.java

I want to make the openCurrentDocument method in the DocxTextPlugin to be public. Then I can use it in Kassenbuch (and possibly other) plugin(s) to create directly a PDF document, when I run the RCPTT GUI-Tests.

[24027] Make convertDocx2Pdf to enable docx textplug to use it

---

bundles/ch.elexis.core.jpa.datasource/src/ch/elexis/core/jpa/datasource/internal/DataSourceConnectionParser.java

This is needed for the RCPTT GUI tests to dump a h2 while running

[24207] Add AUTO_SERVER for h2

---

bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/util/GenericObjectDropTarget.java

Changed the Table background highlight back to the style used in Elexis 3.7, because we couldn't read the "Diagnosis" and "Billing" tables very well. 
https://redmine.medelexis.ch/issues/24908

[24908] kons red

---

bundles/ch.elexis.core.ui.e4/src/ch/elexis/core/ui/e4/dialog/IContactSelectorDialog.java

part (1) - concurrently searching for first and last name & searching for birthdate only
notice: doesn't necessarily search in two separate descriptions; e.g. search for 'ba la' also finds 'Alabaster Asterix'

[25578] optimizing search dialog in pea-view

---

bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties

Within bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties the following Platzhalter names were not working because they contained whitespaces and apostrophes:
RezeptBlatt_4 = [Lignes de l'ordonnance]
RezeptBlatt_4_Extended = [Lignes de recetteExt]
RezeptBlatt_6 = [Liste des m\u00E9dicaments]
RezeptBlatt_6_Extended = [Liste des m\u00E9dicamentsExt]
The names were replaced by:
RezeptBlatt_4 = [medicament]
RezeptBlatt_4_Extended = [medicamentExt]
RezeptBlatt_6 = [medication]
RezeptBlatt_6_Extended = [medicationExt]

Replaced french Platzhalter names

---

bundles/ch.elexis.core.jpa/db/v3.12/elexisdb_update.xml
bundles/ch.elexis.core.services/src/ch/elexis/core/services/StickerService.java

Der Eintrag in die Tabelle ETIKETTEN_OBJCLASS_LINK wird benötigt, damit in der Patienten View nach diesem Sticker gefiltert werden kann.

[26531] do not display mediorder sticker

---

bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FallDetailBlatt2.java

Beim Testen ist aufgefallen, dass beim Öffnen des Falldetails von einem Fall das Lastupdate aktualisiert wird, oder auch beim Auswählen der Checkbox "Keine elektronische Zustellung" wird der Fall erst aktualisiert, wenn man das Falldetail View erneut öffnet.
Die Änderungen sollten die zwei Probleme lösen.

[26513] fix updating of fall in falldetail

---

bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/preferences/UserSettings2.java
bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/Patientenblatt2.java

1. Checkbox in PreferencePage
2. Button selection logic
3. Two new params in 'config' will be used (one for boolean and one for custom global fields)
4. Logic: 
- if bool true, show global fields in preference page and use those.
- if bool true, check if global fields param has values / is not empty
- - if no values / empty, get all custom userfields from 'userconfig' and append them all into one global field. save it in 'config' too.
- - global field in 'config' can be changed too.
- user can choose to go back and use their own custom fields set in 'userconfig' by toggling the checkbox

[26635] Patientendetails - global custom fields

---

bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/preferences/UserSettings2.java
bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/Patientenblatt2.java

- removed the whole stickerComposite field width setting since it did not fully fix the scaling issue, and just set the maxColumns of the composite to 2 so the layout looks better.
- Added a valid range for the minimum width in the pref page
- Also set a widthhint for the inpAdresse field. I noticed during testing that when the text is very long it interferes with the width of the view.

[26442] stickerComposite rework, inpAdresse width, mindwith input range

---

bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/ReminderListsView.java

Noticed while testing that you cannot assign a reminder back to all via drag and dropping into the all reminders area.
this should add the ability.

[26738] add drag and drop support for general patients

---

bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/ReminderListsView.java

- fix: isChecked on the action calls the wrong one instead of the specific one.
- - calling this.isChecked() instead works.
- fix: when checking a filter using global config, the other tables and its filters dont refresh
- - new method which refreshes all filter actions when the refresh() is called.
- fix: resetOtherFilters only reset the filters of a specific table with the given parameter
- - the logic is the same, now additionally if useGlobalFilters, then reset the filters of each area. i used entryset for this.

[26738] reminder beta global filter change refreshes all actions

---

bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/ReminderListsView.java

- deleteReminderAction and ReminderStatus SubMenu both use the getSelection to check if an element is selected.
they both should check only the selection of the viewer the menu is assigned to.
I achieved this by adding a method getViewerForId(String id), which returns the viewer with the given id from a HashMap which has all viewers.
- fix patient change reminder query
before, the query gets the patient related reminders which are assigned to the active mandator.
after, the query should *also* get patient related reminders which are assigned to ALL
- adjusted the custom time action dialog for improved experience
can only select dates from *today*
show a text as the title of the dialog
- fix duedate filter query
before, only add comparator less or equal filter to reminder
after, it should …

[26738] reminders beta fixes and improvements

---

bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
bundles/ch.elexis.core.services/src/ch/elexis/core/services/StickerService.java
bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/KontaktBlatt.java
bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/Patientenblatt2.java
bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/propertypage/PatientPropertyPage.java
bundles/ch.elexis.core/src/ch/elexis/core/model/StickerConstants.java
bundles/ch.elexis.core/src/ch/elexis/core/services/IStickerService.java

Ist der neue pr für https://github.com/elexis/elexis-3-core/pull/695

[26544] dialog on mail change of activated mediorder patient
