- ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/RolesToAccessRightsPreferencePage.java
- ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/UserManagementPreferencePage.java
Some small UI-changes requested by Peter Schönbucher
> Preferences

- ch.elexis.core.data.tests/src/ch/elexis/data/Test_LabItem.java
- ch.elexis.core.data.tests/src/ch/elexis/data/Test_Query.java
- ch.elexis.core.data/src/ch/elexis/data/PersistentObject.java
- ch.elexis.core.data/src/ch/elexis/data/Query.java
* Added logging debug message to measure time of a query
* Added test for prepared statement in Test_Query.java
* Added test for query.orderBy in Test_Query.java
* Added query for mapped fields as proposed by marco
* Added JUnit-Test testQueryMappedExpression for it
> [5230]Extend query functionality to mapped fields

- ch.elexis.core.data/plugin.xml
- ch.elexis.core.data/src/ch/elexis/core/data/propertyTester/ElexisPropertyTester.java
- ch.elexis.core.ui/plugin.xml
> [5707] Bei Standalone Modus soll LockingSymbol (rechts unten) gar nicht

- ch.elexis.core.data/src/ch/elexis/core/data/util/BillingUtil.java
> [5861] Wert der total Splate auf der Rechnungsvorschlag-View stimmt

- ch.elexis.core.data/src/ch/elexis/core/data/service/internal/LocalDocumentService.java
> [6068] Lokales editieren von bestimmten Dateitypen funktioniert noch

- ch.elexis.core.ui/build.properties
- ch.elexis.core.ui/fragment.e4xmi
- ch.elexis.core.ui/plugin.xml
- ch.elexis.core.ui/src/ch/elexis/core/ui/coolbar/MandantSelectionContributionItem.java
> [6618] Mandanten Auswahl und Updatesite Anzeige im Menubar werden nicht

- ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/RolesToAccessRightsPreferencePage.java
- ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/UserManagementPreferencePage.java
- ch.elexis.core.ui/src/ch/elexis/core/ui/util/BooleanNotConverter.java
bitte auf mac überprüfen UI Änderung. (Sashform)
> [6744] Benutzerverwaltung Darstellungsproblem

- ch.elexis.core.documents/src/ch/elexis/core/documents/DocumentStore.java
- ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/dialogs/SendMailDialog.java
- ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/handlers/SendMailHandler.java
- ch.elexis.core.ui.documents/META-INF/MANIFEST.MF
- ch.elexis.core.ui.documents/OSGI-INF/ch.elexis.core.ui.documents.service.OutboxElementServiceHolder.xml
- ch.elexis.core.ui.documents/build.properties
- ch.elexis.core.ui.documents/plugin.xml
- ch.elexis.core.ui.documents/src/ch/elexis/core/ui/documents/handler/DocumentSendAsMailHandler.java
- ch.elexis.core.ui.documents/src/ch/elexis/core/ui/documents/handler/OutboxHandler.java
- ch.elexis.core.ui.documents/src/ch/elexis/core/ui/documents/service/OutboxElementServiceHolder.java
- ch.elexis.core.ui/src/ch/elexis/core/ui/commands/SendBriefAsMailHandler.java
> [6131] XDM_Outbox_inbox BETA

- ch.elexis.core.data/src/ch/elexis/core/data/util/BillingUtil.java
- ch.elexis.core.data/src/ch/elexis/data/dto/InvoiceHistoryEntryDTO.java
- ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/FallSelectionDialog.java
- ch.elexis.core.ui/src/ch/elexis/core/ui/views/rechnung/InvoiceCorrectionView.java
- ch.elexis.core.ui/src/ch/elexis/core/ui/views/rechnung/InvoiceCorrectionWizard.java
Diese Anforderungen von Ticket #8714:
*Zeilenumbruch bei Bemerkungen einführen (Feature)
*Bei Fallauswahl geschlossene Fälle nicht anzeigen (Feature)
wurden im Zuge vom Feature Ticket #8780 mit entwickelt -> Zielversion 3.3. 
(Wurde auch im Ticket vermerkt)
> [8714] [8780] Kons auf anderen Fall transferieren

- ch.elexis.core.data.tests/readme.textile
- ch.elexis.core.data/rsc/.gitignore
Just a bit more clear and right username for the database access.
> corrected informations for test preparation and launch

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
Mostly strings capitalized and small corrections.
> Translation #5

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
Strings capitalized + some minor corrections.
> Translation #6

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
Mostly strings capitalized and minor additions in italian
> Translation #7

- bundles/ch.elexis.core.data/src/ch/elexis/data/Konsultation.java
> Fix DateTimeParseException exception in Konsultation

- bundles/ch.elexis.core.data/src/ch/elexis/data/PersistentObject.java
- bundles/ch.elexis.core.data/src/ch/elexis/data/Query.java
- tests/ch.elexis.core.data.tests/src/ch/elexis/data/Test_Query.java
Gemapped felder werden nicht korrekt aus dem Cache gelesen.
> [14887] Performance Analyse Agenda

- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FallDetailBlatt2.java
Die Anpassungen sind nicht gross.
Ich habe auch getestet, dass ich damit mit RCPTT das GUI testen kann. Was ich mit RCPTT nicht testen kann, ist wenn der Benutzer ein (nicht leeres) Enddatum anwählt und im PopUpDialog auf "Löschen druckt", damit der Fall von Geschlossen wieder auf offen geht. Da betrifft die neue Zeile 954: actFall.setEndDatum(null);
> [14803] Use Nebula CDateTime for Neuer Fall Dialog

- bundles/ch.elexis.core.application/plugin.xml
- bundles/ch.elexis.core.model/src/ch/elexis/core/model/Patient.java
- bundles/ch.elexis.core.test.context/src/ch/elexis/core/test/context/TestContext.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/actions/GlobalEventDispatcher.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/processor/ElexisProcessor.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/services/internal/Context.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/services/internal/ContextService.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/util/FallComparator.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FaelleView.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/provider/FaelleContentProvider.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/provider/FaelleLabelProvider.java
- bundles/ch.elexis.core/src/ch/elexis/core/services/IContext.java
includes also eventhandling from po to jpa
> [15156] FaelleView Fall to ICoverage

- bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/Patientenblatt2.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/KonsDetailView.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/controls/StickerComposite.java
Damit die Hintergründe der sticker auch bei allen 3 views gleich aussieht, musste ich da auch anpassungen machen mit SWT.COLOR_WIDGET_BACKGROUND. Zusätzlich habe ich noch ein Refresh mechanismus eingebaut, sonst ist das hinzufügen bzw entfernen der Sticker nicht sofort sichtbar.
> [15587] Sticker Bearbeitung über Patienten/Kons ermöglichen

- bundles/ch.elexis.core.importer.div/src/ch/elexis/core/importer/div/importers/multifile/strategy/FileImportStrategyUtil.java
- bundles/ch.elexis.core/src/ch/elexis/core/utils/FileUtil.java
> [14972] MediPort - Rückweisungen archivieren

- bundles/ch.elexis.core.data/src/ch/elexis/data/Rechnung.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/rechnung/RnDialogs.java
refactoring, logic aus medelexis rechnungsutil (buchhaltung)
> [14889] 3faches Rechnunsstorno

- bundles/ch.elexis.core.ui/plugin.xml
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/actions/GlobalActions.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/commands/PrintContactLabelHandler.java
This pull request continues the concept of https://github.com/elexis/elexis-3-core/commit/1c9c2bb5ddb49975d9857184260712420ee300e9
> Use command framework for contact printing action

- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/inputs/DateTimeFieldEditor.java
https://bugs.eclipse.org/bugs/show_bug.cgi?id=194162 angepasst für DateCfgs aus Strings (TimeTool.Compact_Date)
> [10716] Änderungswünsche FIRE - cfgparam

- bundles/ch.elexis.core.application/src/ch/elexis/core/application/Desk.java
- bundles/ch.elexis.core.data/src/ch/elexis/data/PersistentObject.java
- bundles/ch.elexis.core.jpa/db/elexisdb_create_initial.xml
- bundles/ch.elexis.core.jpa/src/ch/elexis/core/jpa/liquibase/LiquibaseDBInitializer.java
@Thomas im split modus ist es einfacher zu verstehen. bitte im ticket den kommentar beachten
> [16344] DBUpdate entfernen, Test Liquibase eine valide DB initalisiert

- bundles/ch.elexis.core.jpa.entities/META-INF/persistence.xml
- bundles/ch.elexis.core.jpa.entities/src/ch/elexis/core/jpa/entities/DBLog.java
- bundles/ch.elexis.core.jpa/META-INF/MANIFEST.MF
- bundles/ch.elexis.core.jpa/OSGI-INF/ch.elexis.core.jpa.model.service.holder.ContextServiceHolder.xml
- bundles/ch.elexis.core.jpa/OSGI-INF/ch.elexis.core.jpa.model.service.holder.StoreToStringServiceHolder.xml
- bundles/ch.elexis.core.jpa/src/ch/elexis/core/jpa/model/adapter/AbstractModelService.java
- bundles/ch.elexis.core.jpa/src/ch/elexis/core/jpa/model/service/holder/ContextServiceHolder.java
- bundles/ch.elexis.core.jpa/src/ch/elexis/core/jpa/model/service/holder/StoreToStringServiceHolder.java
offene Todos sollten es besprechen.
> [17045] PO delete - DB Log Eintrag mit NoPo

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
- bundles/ch.elexis.core.pdfbox.ui/src/ch/elexis/core/pdfbox/ui/parts/PdfPreviewPart.java
- bundles/ch.elexis.core.pdfbox.ui/src/ch/elexis/core/pdfbox/ui/parts/PdfPreviewPartLoadHandler.java
PDF preview fix and added language support for label text
> [23318] PDF fix

- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/BriefAuswahl.java
> [23866] Briefauswahl sorted by date

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/Messages.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/TextView.java
Display recipient surname, lastname and place by adding new letter in the view. Internationalized "to".
Moved code in separated method as requested.
> [23910] Letter Selection display recipient name and place

- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/BriefAuswahl.java
Fixed exact sort order by lastupdate
> [23866] Added return statement for sorting exact date

- bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/views/LabNotSeenView.java
sorting table view "Labor neu"
> [23796] sort table view Labor neu

- bundles/ch.elexis.core.jpa/db/elexisdb_create_optional.xml
- ch.elexis.core.p2site/pom.xml
Tested via RCPTT-GUI Test.
Avoids errors like ch.rgw.tools.JdbcLinkSyntaxException
> [17098] Create CSTGROUPS and CSTGROUP_LABITEM_JOINT in liquibase

- bundles/ch.elexis.core.ui.tasks/src/ch/elexis/core/ui/tasks/parts/TaskConfigurationPart.java
sorting table task configuration
> [23796] Sorting table Task configuration

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
- bundles/ch.elexis.core.ui/plugin_de.properties
- bundles/ch.elexis.core.ui/plugin_it.properties
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/commands/BillingProposalViewCreateBillsHandler.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/rechnung/Messages.java
Added question Dialog, if you are sure, if you want to create a bill. + Changed Tooltip.
> [24340] Added question Dialog, if you want to create a bill

- ch.elexis.target/ide.target
> [24209] Update hotspot.jre to 17.0

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/rechnung/Messages.java
Internationalized Text for the "[24420] Editable Textdialog for invoice texts" PR
> [24420] Internationalized Text for "[24420] Editable Textdialog" PR

- bundles/ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/preference/SerializableFile.java
- bundles/ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/preference/SerializableFileUtil.java
- bundles/ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/preference/TextTemplates.java
Habe den alten pr #519 geschlossen.
> [25214] add pdf files to texttemplate

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
Das ist noch der andre Teil für das Projekt Barcode zu Medi-Print hinzufügen
> [25339] Barcode zu Medi-Print hinzugefügt

- bundles/ch.elexis.core.mail.ui/META-INF/MANIFEST.MF
- bundles/ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/preference/Preference.java
- bundles/ch.elexis.core.mail/META-INF/MANIFEST.MF
- bundles/ch.elexis.core.mail/OSGI-INF/ch.elexis.core.mail.internal.MailTransporter.xml
- bundles/ch.elexis.core.mail/build.properties
- bundles/ch.elexis.core.mail/src/ch/elexis/core/mail/PreferenceConstants.java
- bundles/ch.elexis.core.mail/src/ch/elexis/core/mail/internal/MailTransporter.java
pr für agenda reminder PreferencePage ist in gitlab
> [25354] MailTransporter - agenda reminder

- bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/dialogs/PatientErfassenDialog.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/util/FormatValidator.java
> [25355] AHV number and email for new patient

- bundles/ch.elexis.core.ui.e4/src/ch/elexis/core/ui/e4/dialog/IContactSelectorDialog.java
currently works for:
- 07.09.23
- 07.09.2023
- 7.9.23
- 7.9.2023
- 07-09-23
- 07-09-2023
- 7-9-23
- 7-9-2023
- 07/09/23
- 07/09/2023
- 7/9/23
- 7/9/2023
> [25578] optimizing duplicate dialog in pea view (part 2, birth date)

- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/KonsDetailView.java
I only changed the foreground color to white
> [25726] schriftfarbe aendern

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
aufgabe war es mich über fehlermeldungen schlau zu machen ,hier sind aber schonmal die behebungen von NR 4-7  , 1-4 habe ich ins ticket komentiert (4-7 auch)
> [25820] solved errorcode Nr 4-7

- bundles/ch.rgw.utility/src/ch/rgw/tools/MimeTool.java
Modifications to get the Omnivore's file export to filesystem running on NIXes
> Added UNIX/OpenOffice specific mime types

- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/BrowserView.java
weiter Leitungsfehler korrigiert
> [25986] Http Response Code Überprüfung Favoriten-Leiste angepasst und

- bundles/ch.elexis.core.jpa/db/v3.12/elexisdb_update.xml
To overcome the psql "Error: more than one row returned by a subquery used as an expression"
> Added LIMIT 1 to SQL statement

- bundles/ch.elexis.core.jpa/db/v3.12/elexisdb_update.xml
- bundles/ch.elexis.core.ui.medication/src/ch/elexis/core/ui/medication/views/MedicationTableComposite.java
> [25447] add medicationContribution for mediorder

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
PR für den Aufruf der Messages ist im Base: https://github.com/elexis/elexis-3-base/pull/357
> [26497] add new Message for LG1 order

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FaelleView.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/FallDetailBlatt2.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/Messages.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/provider/FaelleLabelProvider.java
In Fälle soll ein Tooltip sein, welcher das Datum der letzten Änderung zeigt. Dann soll noch im Falldetail nur gespeichert werden, wenn Werte verändert werden.
> [26513] fall lastupdate-tooltip and falldetail saving only when modified

- bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/PatListeContentProvider.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/util/viewers/CommonViewer.java
-sorting by patientNr numerically correct
-button to show more patients only shown at the bottom of list
-when sorting, position set back to top
> [26556] View Patienten patches

- bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/controls/util/DisplayDoubleClickListener.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/DisplayLabDokumenteDialog.java
> [26576] DoubleClickListener angepasst und Extension beim Temp File

- bundles/ch.elexis.core.ui.mediorder/src/ch/elexis/core/ui/mediorder/MediorderPart.java
- bundles/ch.elexis.core/src/ch/elexis/core/common/ElexisEventTopics.java
Gehört zum mr: https://gitlab.medelexis.ch/medelexis/medelexis-3/-/merge_requests/132
> [26587] event for mediorder part refresh

- bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/Patientenblatt2.java
the boolean is now stored in userconfig.
i forgot to fix the if check to check for the boolean in userconfig instead of config.
> [26635] fixed wrong check

- bundles/org.iatrix.help.wiki/src/org/iatrix/help/wiki/Constants.java
> Adjusted URL to the new Wiki page on Github

- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/ReminderListsView.java
- neuer Bereich für Pendenzen ohne Patientenbezug
- tooltiptext für remindertyp
- bei drag n drop vor dem setResponsibleAll confirmation Dialog öffnen
- small refactoring bei paar Stellen
> [26738] reminders beta changes

- bundles/ch.elexis.core.jpa.entities/META-INF/persistence.xml
- bundles/ch.elexis.core.jpa.entities/src/ch/elexis/core/jpa/entities/BestellungEntry.java
- bundles/ch.elexis.core.jpa.entities/src/ch/elexis/core/jpa/entities/OutputLogEntity.java
- bundles/ch.elexis.core.jpa/db/v3.13/elexisdb_update.xml
- bundles/ch.elexis.core.model/src/ch/elexis/core/model/OrderEntry.java
- bundles/ch.elexis.core.model/src/ch/elexis/core/model/OutputLog.java
- bundles/ch.elexis.core.model/src/ch/elexis/core/model/service/CoreModelAdapterFactory.java
- bundles/ch.elexis.core/model/model.ecore
- bundles/ch.elexis.core/model/model.genmodel
- bundles/ch.elexis.core/rsc/acl/ict-administrator.json
- bundles/ch.elexis.core/rsc/acl/medical-user.json
- bundles/ch.elexis.core/src-gen/ch/elexis/core/model/IOrderEntry.java
- bundles/ch.elexis.core/src-gen/ch/elexis/core/model/IOutputLog.java
- bundles/ch.elexis.core/src-gen/ch/elexis/core/model/ModelPackage.java
- bundles/ch.elexis.core/src-gen/ch/elexis/core/model/impl/ModelPackageImpl.java
- bundles/ch.elexis.core/src-gen/ch/elexis/core/model/util/ModelAdapterFactory.java
- bundles/ch.elexis.core/src-gen/ch/elexis/core/model/util/ModelSwitch.java
> [26977] OutputLog zu IOutputLog Interface

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/dialogs/LaborAttachmentAction.java
gehört zu mr: https://gitlab.medelexis.ch/medelexis/medelexis-3/-/merge_requests/214
> [27065] add select and deselect all btn to dialog

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/OrderImportDialog.java
- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/StockManagementPreferencePage.java
- bundles/ch.elexis.core/src/ch/elexis/core/constants/Preferences.java
**gehört zu:** https://github.com/elexis/elexis-3-base/pull/435
> [26834] create article label for rowa output

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
- bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/dialogs/LaborVerordnungDialog.java
- bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/dialogs/Messages.java
> [27179] LaborVerordnungDialog Checkbox hinzugefügt und

- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/Messages.java
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_de.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_en.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_fr.properties
- bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages_it.properties
- bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/controls/LaborOrdersComposite.java
- bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/controls/Messages.java
- bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/dialogs/LaborVerordnungDialog.java
- bundles/ch.elexis.core.ui.laboratory/src/ch/elexis/core/ui/laboratory/dialogs/Messages.java
> [27242] Labor Spalte "Entnahme-/Beobachtungszeitpunkt" hinzugefügt und

- bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/ReminderView.java
> [27354] Pendenzen Menü Option "Alle" zeigt nun erkennbaren aktiven
